### ISSUE TITLE
UI design skills beside my front-end dev knowledge

### ISSUE THREAD

**Issue by mohammedsobhi** [amrsekilly/AMA#4]
if I have a designing knowledge and I can design a neat and beautiful user interface. then if I take some courses in UI design to be more professional, does that give me a plus or an advantage to find a job ... or should I focus on sharpening my development skill only.

**Comment by amrsekilly** [comment]
@mohammedsobhi, as a frontend web developer you don't have to learn UI design, for example, you don't need to learn Sketch, Figma, Photoshop, etc. This might help you, but it's another job. Because most teams have UI designers. So I guess you only have to focus on your development skills + some CSS.
